#!/bin/bash
./setup_linux.sh
./setup_hadoop_user.sh
./add_pubkeys.sh
./disable_ipv6.sh
./install_hadoop.sh
./setup_environment.sh
./hadoop_configuration.sh
./format_namenode.sh
./install_spark.sh
./spark_configure.sh
